# Generated by Django 6.0.5 on 2026-06-01 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIoTNode',
            fields=[
                ('node_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_category', models.CharField(max_length=50)),
                ('dcc_score', models.FloatField(help_text='Device Capability Criterion (0.0 - 1.0)')),
                ('elc_score', models.FloatField(help_text='Energy Limitation Criterion (0.0 - 1.0)')),
                ('msrc_score', models.FloatField(help_text='Minimal Security Requirements (0.0 - 1.0)')),
                ('is_malicious', models.BooleanField(default=False, help_text='Flagged by the ML Model')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_user', models.FloatField(default=0.5, help_text='User Intention Score')),
                ('t_device', models.FloatField(default=0.5, help_text='Device Hardware Score')),
                ('t_service', models.FloatField(default=0.5, help_text='Service Quality Score')),
                ('t_final', models.FloatField(default=0.5, help_text='Aggregated Multidimensional Score')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='network_state.siotnode')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(0, 'Bad'), (1, 'Good')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mitigated', models.BooleanField(default=False, help_text='True if rating was nullified by countermeasure')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to='network_state.siotnode')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='network_state.siotnode')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'requester'], name='network_sta_provide_d63498_idx')],
            },
        ),
    ]
