# Generated by Django 6.0.5 on 2026-06-15 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDimension',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dcc_score', models.FloatField(default=0.5)),
                ('elc_score', models.FloatField(default=0.5)),
                ('msrc_score', models.FloatField(default=0.5)),
                ('device_trust_score', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDimension',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('latency', models.FloatField(default=0.5)),
                ('response_time', models.FloatField(default=0.5)),
                ('successfulness', models.FloatField(default=0.5)),
                ('availability', models.FloatField(default=0.5)),
                ('service_trust_score', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='UserDimension',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('credibility', models.FloatField(default=0.5)),
                ('reputation', models.FloatField(default=0.5)),
                ('rating_trend', models.FloatField(default=0.5)),
                ('fluctuation', models.FloatField(default=0.5)),
                ('user_trust_score', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='SIoTNode',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_malicious', models.BooleanField(default=False, help_text='Flagged by the ML Model')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_state.devicedimension')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_state.servicedimension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_state.userdimension')),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_user', models.FloatField(default=0.5, help_text='User Intention Score')),
                ('t_device', models.FloatField(default=0.5, help_text='Device Hardware Score')),
                ('t_service', models.FloatField(default=0.5, help_text='Service Quality Score')),
                ('t_final', models.FloatField(default=0.5, help_text='Aggregated Multidimensional Score')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to='network_state.siotnode')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionHistory',
            fields=[
                ('interaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to='network_state.siotnode')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='network_state.siotnode')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'requester'], name='network_sta_provide_d63498_idx')],
            },
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_strength', models.FloatField(default=0.5)),
                ('similarity', models.FloatField(default=0.5)),
                ('direct_exchange', models.FloatField(default=0.5)),
                ('rating_frequency', models.FloatField(default=0.5)),
                ('recommendation', models.FloatField(default=0.5)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_out', to='network_state.userdimension')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_in', to='network_state.userdimension')),
            ],
            options={
                'indexes': [models.Index(fields=['source_node', 'target_node'], name='network_sta_source__12c761_idx')],
                'unique_together': {('source_node', 'target_node')},
            },
        ),
    ]
