# Generated by Django 6.0.5 on 2026-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_state', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionhistory',
            name='latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='interactionhistory',
            name='response_time_ms',
            field=models.FloatField(default=0.0),
        ),
    ]
