# Generated by Django 6.0.5 on 2026-06-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_state', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdimension',
            old_name='prev_rating_as_requester',
            new_name='prev_qos_provided',
        ),
    ]
