# Generated by Django 6.0.5 on 2026-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_state', '0002_interactionhistory_latency_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionhistory',
            name='ocial_similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
