# Generated by Django 6.0.5 on 2026-06-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_state', '0003_interactionhistory_ocial_similarity_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionhistory',
            old_name='ocial_similarity_score',
            new_name='social_similarity_score',
        ),
    ]
